openapi: 3.0.0
info:
  title: Bugged API Trainer
  version: 1.0.0
  description: API documentation for Bugged API Trainer
paths:
  /login:
    post:
      summary: User login
      description: Allows a user to log in with a username and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
        '400':
          description: Invalid credentials